version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortening
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      target: dev
    command: npx ts-node-dev src/index.ts
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/url_shortening
      JWT_SECRET: dev_secret
      REDIS_URL: redis://redis:6379
      PORT: 3000
    ports:
      - "3001:3000"
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      VITE_API_BASE_URL: http://localhost:3001/api/urls
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
